In [85]:
import numpy as np

In [87]:
elements = ['one', 'two', 'three'] 
weights = [0.2, 0.3, 0.5]

from numpy.random import choice
print(choice(elements, size=10, replace=True, p=weights))

['three' 'one' 'one' 'two' 'three' 'two' 'three' 'three' 'one' 'one']


In [88]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [89]:
X[0]

array([0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
       0.125     , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [90]:
y[:10]

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [91]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier


In [98]:
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=500, 
                          learning_rate=0.1)

In [99]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

0.8155272011680316

In [100]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
AdaBoostClassifier()

In [131]:
params = {"base_estimator__criterion" : ["gini", "entropy"],
          "base_estimator__max_features" : [7,8,],
          "base_estimator__max_depth" : [1,2],
          "n_estimators": [23,24, 25, 26, 27],
          "learning_rate": [0.4, 0.45, 0.5, 0.55, 0.6]
         }

In [ ]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5, n_jobs=7)
grid = grid.fit(X, y)

In [128]:
grid.best_score_

0.8312710911136107

In [129]:
grid.best_params_

{'base_estimator__criterion': 'gini',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 8,
 'learning_rate': 0.6,
 'n_estimators': 26}

In [130]:
grid.best_estimator_.feature_importances_

array([0.19406886, 0.23061462, 0.04090978, 0.05602668, 0.06539204,
       0.06219571, 0.04414943, 0.03733474, 0.02491265, 0.00782351,
       0.        , 0.        , 0.01205415, 0.05311241, 0.01024874,
       0.04730915, 0.        , 0.01836485, 0.00899386, 0.        ,
       0.00761332, 0.03372184, 0.02510816, 0.02004552, 0.        ,
       0.        , 0.        ])