In [2]:
import numpy as np

#### reshape

In [6]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [11]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [12]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [9]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [23]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [25]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

#### flat or flatten()

In [40]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])