In [1]:
import numpy as np

#### all & any

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a<0

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [11]:
np.any(a>5), np.any(a<0)

(True, False)

In [12]:
np.all(a>5) , np.all(a < 10)

(False, True)

#### comparision operation

In [8]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b 

array([False,  True, False], dtype=bool)

In [9]:
test_a == test_b 

array([False, False, False], dtype=bool)

In [10]:
(test_a > test_b).any()

True

In [11]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False], dtype=bool)

In [12]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False], dtype=bool)

In [13]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True], dtype=bool)

In [15]:
a

array([ 1.,  3.,  0.])

In [14]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [22]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [44]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

In [46]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

#### argmax & argmin

In [25]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

In [26]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))