In [1]:
import pandas as pd
import numpy as np

In [4]:
data_source = "dds_ch5_binary-class-dataset.txt"
df = pd.read_table(data_source)

In [5]:
df[:].shape

(54584, 22)

In [6]:
df.dtypes

at_buy_boolean                 int64
at_freq_buy                    int64
at_freq_last24_buy             int64
at_freq_last24_sv              int64
at_freq_last24_sv_int_buy      int64
at_freq_sv                     int64
at_freq_sv_int_buy             int64
at_interval_buy              float64
at_interval_sv               float64
at_interval_sv_int_buy       float64
expected_time_buy            float64
expected_time_sv             float64
expected_time_sv_int_buy     float64
last_buy                       int64
last_sv                        int64
last_sv_int_buy                int64
multiple_buy                   int64
multiple_sv                    int64
multiple_sv_int_buy            int64
uniq_content_links             int64
num_checkins                   int64
y_buy                          int64
dtype: object

In [7]:
df.describe()

at_buy_boolean   at_freq_buy  at_freq_last24_buy  at_freq_last24_sv  \
count    54584.000000  54584.000000        54584.000000       54584.000000   
mean         0.042632      0.052891            0.001942           0.117049   
std          0.202027      0.298157            0.051682           0.822048   
min          0.000000      0.000000            0.000000           0.000000   
25%          0.000000      0.000000            0.000000           0.000000   
50%          0.000000      0.000000            0.000000           0.000000   
75%          0.000000      0.000000            0.000000           0.000000   
max          1.000000     15.000000            4.000000          36.000000   

       at_freq_last24_sv_int_buy    at_freq_sv  at_freq_sv_int_buy  \
count               54584.000000  54584.000000        54584.000000   
mean                    0.023542      1.852777            0.271636   
std                     0.483363      2.921820            2.206286   
min                     0.000000      0.000000            0.000000   
25%                     0.000000      1.000000            0.000000   
50%                     0.000000      1.000000            0.000000   
75%                     0.000000      2.000000            0.000000   
max                    36.000000     84.000000           75.000000   

       at_interval_buy  at_interval_sv  at_interval_sv_int_buy      ...       \
count     54584.000000    54584.000000            54584.000000      ...        
mean          0.210008        5.825610                0.381641      ...        
std           3.922016       17.595442                3.884156      ...        
min           0.000000        0.000000                0.000000      ...        
25%           0.000000        0.000000                0.000000      ...        
50%           0.000000        0.000000                0.000000      ...        
75%           0.000000        0.104167                0.000000      ...        
max         174.625000      184.916700              176.708300      ...        

       expected_time_sv_int_buy      last_buy       last_sv  last_sv_int_buy  \
count              54584.000000  54584.000000  54584.000000     54584.000000   
mean                  -0.953705      2.791221     64.729335         1.790671   
std                    9.792084     17.426907     53.476658        13.042733   
min                 -183.362600      0.000000      0.000000         0.000000   
25%                    0.000000      0.000000     18.000000         0.000000   
50%                    0.000000      0.000000     51.000000         0.000000   
75%                    0.000000      0.000000    105.000000         0.000000   
max                   88.300380    187.000000    188.000000       186.000000   

       multiple_buy   multiple_sv  multiple_sv_int_buy  uniq_content_links  \
count  54584.000000  54584.000000         54584.000000        54584.000000   
mean       0.006357      0.277444             0.032739           86.569343   
std        0.079479      0.447742             0.177953           61.969765   
min        0.000000      0.000000             0.000000           -1.000000   
25%        0.000000      0.000000             0.000000           30.000000   
50%        0.000000      0.000000             0.000000           75.000000   
75%        0.000000      1.000000             0.000000          155.000000   
max        1.000000      1.000000             1.000000          206.000000   

       num_checkins         y_buy  
count  54584.000000  54584.000000  
mean     720.657592      0.004635  
std     1275.727306      0.067924  
min        1.000000      0.000000  
25%      127.000000      0.000000  
50%      319.000000      0.000000  
75%      802.000000      0.000000  
max    37091.000000      1.000000  

[8 rows x 22 columns]

In [8]:
(df.ix[:,:-1].corrwith(df["y_buy"])).sort_values(ascending=False)

at_freq_buy                  0.136255
at_freq_sv_int_buy           0.122409
at_freq_sv                   0.118092
multiple_sv_int_buy          0.116280
at_buy_boolean               0.112434
multiple_buy                 0.109926
at_freq_last24_sv            0.095936
multiple_sv                  0.070968
at_interval_buy              0.068453
at_freq_last24_sv_int_buy    0.064196
last_buy                     0.051738
at_interval_sv_int_buy       0.046691
at_freq_last24_buy           0.018311
last_sv_int_buy              0.016440
expected_time_sv             0.011826
at_interval_sv               0.011096
expected_time_sv_int_buy    -0.004631
num_checkins                -0.007766
uniq_content_links          -0.019238
expected_time_buy           -0.038141
last_sv                     -0.059171
dtype: float64

In [9]:
df.max().sort_values()

at_buy_boolean                   1.00000
multiple_sv_int_buy              1.00000
multiple_sv                      1.00000
multiple_buy                     1.00000
y_buy                            1.00000
at_freq_last24_buy               4.00000
at_freq_buy                     15.00000
at_freq_last24_sv               36.00000
at_freq_last24_sv_int_buy       36.00000
at_freq_sv_int_buy              75.00000
at_freq_sv                      84.00000
expected_time_buy               84.28571
expected_time_sv_int_buy        88.30038
expected_time_sv                91.40192
at_interval_buy                174.62500
at_interval_sv_int_buy         176.70830
at_interval_sv                 184.91670
last_sv_int_buy                186.00000
last_buy                       187.00000
last_sv                        188.00000
uniq_content_links             206.00000
num_checkins                 37091.00000
dtype: float64

In [10]:
y_data = df["y_buy"].values.reshape(-1,1)
y_data[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [11]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
scaled_column = []

for col_name in df.ix[:,:-1].columns:
    if len(df[col_name].unique()) != 2:
        scaled_column.append(col_name)

        
df_scaled = df
df_scaled[scaled_column] = min_max_scaler.fit_transform(df_scaled[scaled_column])
df_scaled[:5]

at_buy_boolean  at_freq_buy  at_freq_last24_buy  at_freq_last24_sv  \
0               0          0.0                 0.0                0.0   
1               0          0.0                 0.0                0.0   
2               0          0.0                 0.0                0.0   
3               0          0.0                 0.0                0.0   
4               0          0.0                 0.0                0.0   

   at_freq_last24_sv_int_buy  at_freq_sv  at_freq_sv_int_buy  at_interval_buy  \
0                        0.0    0.011905                 0.0              0.0   
1                        0.0    0.011905                 0.0              0.0   
2                        0.0    0.011905                 0.0              0.0   
3                        0.0    0.011905                 0.0              0.0   
4                        0.0    0.023810                 0.0              0.0   

   at_interval_sv  at_interval_sv_int_buy  ...    expected_time_sv_int_buy  \
0        0.000000                     0.0  ...                    0.674964   
1        0.000000                     0.0  ...                    0.674964   
2        0.000000                     0.0  ...                    0.674964   
3        0.000000                     0.0  ...                    0.674964   
4        0.002704                     0.0  ...                    0.674964   

   last_buy   last_sv  last_sv_int_buy  multiple_buy  multiple_sv  \
0       0.0  0.563830              0.0             0            0   
1       0.0  0.382979              0.0             0            0   
2       0.0  0.026596              0.0             0            0   
3       0.0  0.031915              0.0             0            0   
4       0.0  0.537234              0.0             0            1   

   multiple_sv_int_buy  uniq_content_links  num_checkins  y_buy  
0                    0            0.821256      0.057401      0  
1                    0            0.748792      0.029631      0  
2                    0            0.024155      0.000297      0  
3                    0            0.729469      0.014505      0  
4                    0            0.502415      0.009733      0  

[5 rows x 22 columns]

In [12]:
x_data = df_scaled.ix[:,:-1].values
x_data[1]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.01190476,  0.        ,  0.        ,  0.        ,  0.        ,
        0.6833858 ,  0.67241512,  0.67496352,  0.        ,  0.38297872,
        0.        ,  0.        ,  0.        ,  0.        ,  0.74879227,
        0.02963063])

In [15]:
from sklearn.cross_validation import KFold
from sklearn import linear_model, datasets
from sklearn.metrics import precision_recall_fscore_support

kf = KFold(y_data.shape[0], n_folds=5,shuffle=True, )
logreg = linear_model.LogisticRegression(fit_intercept=True)

In [23]:
for i, (train_index, test_index) in enumerate(kf):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    X_train, X_test = x_data[train_index], x_data[test_index]
    y_train, y_test = y_data[train_index], y_data[test_index]
    
    logreg.fit(X_train, y_train.ravel())
    
    y_pred = logreg.predict(X_test)
    y_true = y_test.ravel()
    
    print(np.where(y_pred==0))

TRAIN: 43667 TEST: 10917
(array([    0,     1,     2, ..., 10914, 10915, 10916]),)
TRAIN: 43667 TEST: 10917
(array([    0,     1,     2, ..., 10914, 10915, 10916]),)
TRAIN: 43667 TEST: 10917
(array([    0,     1,     2, ..., 10914, 10915, 10916]),)
TRAIN: 43667 TEST: 10917
(array([    0,     1,     2, ..., 10914, 10915, 10916]),)
TRAIN: 43668 TEST: 10916
(array([    0,     1,     2, ..., 10913, 10914, 10915]),)
