In [1]:
import numpy as np
from sklearn.preprocessing import normalize

In [4]:
data = [(0.7,48000,1),(1.9,48000,0),(2.5,60000,1),(4.2,63000,0),(6,76000,0),(6.5,69000,0),(7.5,76000,0),(8.1,88000,0),(8.7,83000,1),(10,83000,1),(0.8,43000,0),(1.8,60000,0),(10,79000,1),(6.1,76000,0),(1.4,50000,0),(9.1,92000,0),(5.8,75000,0),(5.2,69000,0),(1,56000,0),(6,67000,0),(4.9,74000,0),(6.4,63000,1),(6.2,82000,0),(3.3,58000,0),(9.3,90000,1),(5.5,57000,1),(9.1,102000,0),(2.4,54000,0),(8.2,65000,1),(5.3,82000,0),(9.8,107000,0),(1.8,64000,0),(0.6,46000,1),(0.8,48000,0),(8.6,84000,1),(0.6,45000,0),(0.5,30000,1),(7.3,89000,0),(2.5,48000,1),(5.6,76000,0),(7.4,77000,0),(2.7,56000,0),(0.7,48000,0),(1.2,42000,0),(0.2,32000,1),(4.7,56000,1),(2.8,44000,1),(7.6,78000,0),(1.1,63000,0),(8,79000,1),(2.7,56000,0),(6,52000,1),(4.6,56000,0),(2.5,51000,0),(5.7,71000,0),(2.9,65000,0),(1.1,33000,1),(3,62000,0),(4,71000,0),(2.4,61000,0),(7.5,75000,0),(9.7,81000,1),(3.2,62000,0),(7.9,88000,0),(4.7,44000,1),(2.5,55000,0),(1.6,41000,0),(6.7,64000,1),(6.9,66000,1),(7.9,78000,1),(8.1,102000,0),(5.3,48000,1),(8.5,66000,1),(0.2,56000,0),(6,69000,0),(7.5,77000,0),(8,86000,0),(4.4,68000,0),(4.9,75000,0),(1.5,60000,0),(2.2,50000,0),(3.4,49000,1),(4.2,70000,0),(7.7,98000,0),(8.2,85000,0),(5.4,88000,0),(0.1,46000,0),(1.5,37000,0),(6.3,86000,0),(3.7,57000,0),(8.4,85000,0),(2,42000,0),(5.8,69000,1),(2.7,64000,0),(3.1,63000,0),(1.9,48000,0),(10,72000,1),(0.2,45000,0),(8.6,95000,0),(1.5,64000,0),(9.8,95000,0),(5.3,65000,0),(7.5,80000,0),(9.9,91000,0),(9.7,50000,1),(2.8,68000,0),(3.6,58000,0),(3.9,74000,0),(4.4,76000,0),(2.5,49000,0),(7.2,81000,0),(5.2,60000,1),(2.4,62000,0),(8.9,94000,0),(2.4,63000,0),(6.8,69000,1),(6.5,77000,0),(7,86000,0),(9.4,94000,0),(7.8,72000,1),(0.2,53000,0),(10,97000,0),(5.5,65000,0),(7.7,71000,1),(8.1,66000,1),(9.8,91000,0),(8,84000,0),(2.7,55000,0),(2.8,62000,0),(9.4,79000,0),(2.5,57000,0),(7.4,70000,1),(2.1,47000,0),(5.3,62000,1),(6.3,79000,0),(6.8,58000,1),(5.7,80000,0),(2.2,61000,0),(4.8,62000,0),(3.7,64000,0),(4.1,85000,0),(2.3,51000,0),(3.5,58000,0),(0.9,43000,0),(0.9,54000,0),(4.5,74000,0),(6.5,55000,1),(4.1,41000,1),(7.1,73000,0),(1.1,66000,0),(9.1,81000,1),(8,69000,1),(7.3,72000,1),(3.3,50000,0),(3.9,58000,0),(2.6,49000,0),(1.6,78000,0),(0.7,56000,0),(2.1,36000,1),(7.5,90000,0),(4.8,59000,1),(8.9,95000,0),(6.2,72000,0),(6.3,63000,0),(9.1,100000,0),(7.3,61000,1),(5.6,74000,0),(0.5,66000,0),(1.1,59000,0),(5.1,61000,0),(6.2,70000,0),(6.6,56000,1),(6.3,76000,0),(6.5,78000,0),(5.1,59000,0),(9.5,74000,1),(4.5,64000,0),(2,54000,0),(1,52000,0),(4,69000,0),(6.5,76000,0),(3,60000,0),(4.5,63000,0),(7.8,70000,0),(3.9,60000,1),(0.8,51000,0),(4.2,78000,0),(1.1,54000,0),(6.2,60000,0),(2.9,59000,0),(2.1,52000,0),(8.2,87000,0),(4.8,73000,0),(2.2,42000,1),(9.1,98000,0),(6.5,84000,0),(6.9,73000,0),(5.1,72000,0),(9.1,69000,1),(9.8,79000,1),]
data = np.array(list(map(list, data))) # change tuples to lists
data[:5]

array([[  7.00000000e-01,   4.80000000e+04,   1.00000000e+00],
       [  1.90000000e+00,   4.80000000e+04,   0.00000000e+00],
       [  2.50000000e+00,   6.00000000e+04,   1.00000000e+00],
       [  4.20000000e+00,   6.30000000e+04,   0.00000000e+00],
       [  6.00000000e+00,   7.60000000e+04,   0.00000000e+00]])

In [6]:
data[:, :2] = normalize(data[:, :2], axis=0)
data[:5]

array([[ 0.00861027,  0.04956583,  1.        ],
       [ 0.02337075,  0.04956583,  0.        ],
       [ 0.03075098,  0.06195729,  1.        ],
       [ 0.05166165,  0.06505516,  0.        ],
       [ 0.07380236,  0.07847924,  0.        ]])

In [9]:
x_data = data[:, :2]
x_data = np.insert(x_data, 0 , 1, axis=1)
y_data = data[:, -1]
y_data = y_data.reshape(y_data.shape[0], 1)
y_data.shape

(200, 1)

In [18]:
def compute_cost(x, y, theta):
    m = y.shape[0]
    J = (-1.0 /m )* (y.T.dot(np.log(hypothesis_function(x,theta))) + (1-y).T.dot(np.log(1- hypothesis_function(x,theta))))
    
    return (-1.0 /m )* (y * np.log(hypothesis_function(x,theta)) + (1-y) * np.log(1- hypothesis_function(x,theta))).sum()

def sigmoid(z):
    return 1 / (1 + np.exp(z))

def hypothesis_function(x, theta):
    z = (np.dot(-x,theta))    
    return sigmoid(z)
    
def minimize_gradient(x, y, theta, iterations=100000, alpha=0.01):
    m = y.size
    cost_history = []
    theta_history = []
    
    for _ in range(iterations):
        original_theta = theta
        for i in range(theta.size):
            partial_marginal = x[:, i].reshape(x.shape[0], 1)
            delta = hypothesis_function(x, original_theta) - y
            grad_i = delta.T.dot(partial_marginal)
            
            theta[i] = theta[i] - (alpha  * grad_i)
        
        if (_ % 10000) == 0:
            theta_history.append(theta)
            cost_history.append(compute_cost(x, y, theta))

    return theta, np.array(cost_history), np.array(theta_history)

In [31]:
theta_initial = np.ones([3,1])
theta, cost_history, theta_history = minimize_gradient(
    x_data, y_data,theta_initial, 1000000, 0.01)

In [32]:
print("theta", theta)
print(cost_history)

theta [[   8.81177075]
 [ 129.28824414]
 [-273.95341852]]
[ 0.72561111  0.45703206  0.40330577  0.37154977  0.35113381  0.33717045
  0.32716855  0.31974613  0.31408292  0.30966483  0.30615504  0.3033246
  0.30101302  0.29910481  0.29751499  0.2961798   0.29505058  0.29408968
  0.29326753  0.29256066  0.29195027  0.29142112  0.29096076  0.29055898
  0.29020728  0.28989861  0.28962703  0.28938756  0.28917596  0.28898863
  0.2888225   0.28867492  0.28854363  0.28842666  0.28832232  0.28822913
  0.2881458   0.28807121  0.28800437  0.28794443  0.28789063  0.28784229
  0.28779884  0.28775974  0.28772454  0.28769282  0.28766424  0.28763845
  0.28761518  0.28759417  0.28757519  0.28755804  0.28754253  0.2875285
  0.28751581  0.28750432  0.28749391  0.28748449  0.28747595  0.28746821
  0.2874612   0.28745483  0.28744906  0.28744383  0.28743908  0.28743476
  0.28743085  0.28742729  0.28742406  0.28742113  0.28741846  0.28741604
  0.28741384  0.28741184  0.28741002  0.28740837  0.28740687  0.2874

In [33]:
sum((sigmoid(-x_data.dot(theta)) > 0.5) == y_data) / y_data.shape[0]

array([ 0.895])