In [8]:
from collections import Counter, defaultdict
import math, random, re, glob

In [9]:
def get_subject_data(path):
    data = []

    # regex for stripping out the leading "Subject:" and any spaces after it
    subject_regex = re.compile(r"^Subject:\s+")

    # glob.glob returns every filename that matches the wildcarded path
    for fn in glob.glob(path):
        is_spam = "ham" not in fn

        with open(fn,'r',encoding='ISO-8859-1') as file:
            for line in file:
                if line.startswith("Subject:"):
                    subject = subject_regex.sub("", line).strip()
                    data.append((subject, is_spam))
                    # 폴더에서 하나의 파일의 제목을 subject에 그 파일의 스팸 여부를 data에 저장합니다.

    return data

In [10]:
data = get_subject_data(r"data/*/*")
data[:5]

[('Re: New Sequences Window', False),
 ('[zzzzteana] RE: Alexander', False),
 ('[zzzzteana] Moscow bomber', False),
 ("[IRR] Klez: The Virus That  Won't Die", False),
 ('Re: Insert signature', False)]

In [11]:
text_data = []
result_data = []
for line in data:
    text_data.append(line[0])
    result_data.append(line[1])
    
text_data[0], result_data[0]

('Re: New Sequences Window', False)

In [64]:
y_example_text = ["Sports", "Not sports","Sports","Sports","Not sports"]
y_example = [1 if c=="Sports" else 0 for c in y_example_text ]
text_example = ["A great game game", "The The election was over",
                "Very clean game match",
                "A clean but forgettable game game","It was a close election", ]


countvect_example =  CountVectorizer()
X_example = countvect_example.fit_transform(text_example)
countvect_example.get_feature_names()[:8]

['but', 'clean', 'close', 'election', 'forgettable', 'game', 'great', 'it']

In [65]:
X_example.toarray()

array([[0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [66]:
y_example

[1, 0, 1, 1, 0]

In [78]:
from sklearn.naive_bayes import BernoulliNB

clf = BernoulliNB(binarize=0)
clf.fit(X_example, y_example)
clf.class_log_prior_ 

array([-0.91629073, -0.51082562])

In [70]:
clf.class_count_  

array([ 2.,  3.])

In [72]:
clf.feature_log_prob_  

array([[-1.38629436, -1.38629436, -0.69314718, -0.28768207, -1.38629436,
        -1.38629436, -1.38629436, -0.69314718, -1.38629436, -0.69314718,
        -0.69314718, -1.38629436, -0.28768207],
       [-0.91629073, -0.51082562, -1.60943791, -1.60943791, -0.91629073,
        -0.22314355, -0.91629073, -1.60943791, -0.91629073, -1.60943791,
        -1.60943791, -0.91629073, -1.60943791]])

In [79]:
clf.feature_count_

array([[ 0.,  0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  2.],
       [ 1.,  2.,  0.,  0.,  1.,  3.,  1.,  0.,  1.,  0.,  0.,  1.,  0.]])

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

count_ngrams = CountVectorizer(
    ngram_range=(1,3), analyzer="word", binary="False", stop_words="english")
X = count_ngrams.fit_transform(text_data)
X.toarray() 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
count_ngrams.get_feature_names()[:5]

['00', '00 00', '00 lists', '00 lists sourceforge', '00 overworked']

In [60]:
import numpy as np

Y = [1 if data == True else 0 for data in result_data  ]
Y = np.array(Y)
Y

array([0, 0, 0, ..., 1, 1, 1])

In [21]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.model_selection import KFold
from sklearn import linear_model, datasets
from sklearn.metrics import precision_recall_fscore_support

In [19]:
kf = KFold(Y.shape[0], n_folds=5,shuffle=True, )
clf = BernoulliNB()

NameError: name 'KFold' is not defined

In [ ]:
for i, (train_index, test_index) in enumerate(kf):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    
    clf.fit(X_train, y_train.ravel())
    
    
    from sklearn.metrics import accuracy_score
    print(accuracy_score(clf.predict(X_test), y_test))

In [ ]:
kf = KFold(Y.shape[0], n_folds=5,shuffle=True, )
clf = MultinomialNB()
# clf = BernoulliNB()
# clf = GaussianNB()