<img src=https://cdn-images-1.medium.com/max/1000/1*t_CY-Etmo1vZ8T-Kie4PRw.png>

https://medium.com/@allenckim/understanding-axis-in-numpy-cced18591be0

In [4]:
# Axis Test
import numpy as np

DATA_EXAMPLE = np.array([[ 1., 1,  1],
               [ 2,  2,  2],
               [ 3, 3, 3]])

In [8]:
DATA_EXAMPLE.sum(axis=1)

array([ 3.,  6.,  9.])

In [6]:
DATA_EXAMPLE.mean(axis=1)

array([ 1.,  2.,  3.])

In [7]:
# Axis Test

DATA_EXAMPLE = np.array([[[ 1., 1,  1],
               [ 1,  1,  1],
               [ 1, 1, 1]],
                       [[ 2., 2,  2],
               [ 2,  2,  2],
               [ 2, 2, 2]],
                       [[ 3, 3,  3],
               [ 3,  3,  3],
               [ 3, 3, 3]]])

In [9]:
DATA_EXAMPLE.mean(axis=0)

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [10]:
DATA_EXAMPLE.mean(axis=1)

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [11]:
DATA_EXAMPLE.mean(axis=2)

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])