In [1]:
# Data from https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

In [2]:
import pandas as pd
import numpy as np

In [3]:
columns = ["id", "diagnosis"] + [str("r"+str(i)) for i in range(30)]
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data", names=columns)
df.head(5)

id diagnosis     r0     r1      r2      r3       r4       r5      r6  \
0    842302         M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517         M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903         M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301         M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402         M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        r7   ...       r20    r21     r22     r23     r24     r25     r26  \
0  0.14710   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.10520   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.10430   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

      r27     r28      r29  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 32 columns]

In [4]:
X_raw = df.loc[:,columns[2:]].values
Y_raw = df.loc[:,columns[1]].values
X_raw[:2],Y_raw[:2]

(array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02,
           1.00100000e+03,   1.18400000e-01,   2.77600000e-01,
           3.00100000e-01,   1.47100000e-01,   2.41900000e-01,
           7.87100000e-02,   1.09500000e+00,   9.05300000e-01,
           8.58900000e+00,   1.53400000e+02,   6.39900000e-03,
           4.90400000e-02,   5.37300000e-02,   1.58700000e-02,
           3.00300000e-02,   6.19300000e-03,   2.53800000e+01,
           1.73300000e+01,   1.84600000e+02,   2.01900000e+03,
           1.62200000e-01,   6.65600000e-01,   7.11900000e-01,
           2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
        [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02,
           1.32600000e+03,   8.47400000e-02,   7.86400000e-02,
           8.69000000e-02,   7.01700000e-02,   1.81200000e-01,
           5.66700000e-02,   5.43500000e-01,   7.33900000e-01,
           3.39800000e+00,   7.40800000e+01,   5.22500000e-03,
           1.30800000e-02,   1.86000000e-02,   1.34000

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y_raw)
Y[:30], Y_raw[:30]

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1]),
 array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
        'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
        'M', 'M', 'M', 'M'], dtype=object))

In [6]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer

import numpy as np
X_scale = preprocessing.scale(X_raw, axis=0)
X_std = StandardScaler().fit_transform(X_raw)
X_min_max = MinMaxScaler(feature_range=(0,5)).fit_transform(X_raw)

#http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler
#http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler
#http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html#sklearn.preprocessing.Normalizer   

In [7]:
X_raw[0], X_scale[0], X_std[0], X_min_max[0]

(array([  1.79900000e+01,   1.03800000e+01,   1.22800000e+02,
          1.00100000e+03,   1.18400000e-01,   2.77600000e-01,
          3.00100000e-01,   1.47100000e-01,   2.41900000e-01,
          7.87100000e-02,   1.09500000e+00,   9.05300000e-01,
          8.58900000e+00,   1.53400000e+02,   6.39900000e-03,
          4.90400000e-02,   5.37300000e-02,   1.58700000e-02,
          3.00300000e-02,   6.19300000e-03,   2.53800000e+01,
          1.73300000e+01,   1.84600000e+02,   2.01900000e+03,
          1.62200000e-01,   6.65600000e-01,   7.11900000e-01,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01]),
 array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
         3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
         2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
         1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
         1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
         2.61

In [8]:
X = X_std

In [9]:
len(Y)

569

In [10]:
random_index = np.arange(569)
np.random.shuffle(random_index)
random_index[:100]

array([476, 171, 246, 414, 254, 288, 360, 441, 386, 185, 201, 112, 194,
       458,  30, 526, 188, 355, 563, 334, 510,   2, 140, 547, 169, 170,
       564, 128, 265, 223, 311,  36, 309, 183, 228,  66, 211,  28, 186,
       484, 501, 109, 300,   9,  10, 489, 352, 348,  56, 398, 363, 301,
       339, 373, 231, 336, 506, 545, 307, 328, 338, 565, 377, 533, 364,
       347,  94, 528,  39, 423, 493, 428, 235, 111, 372, 292, 137, 512,
       544, 400, 420, 549, 190, 217, 270, 286, 405,  96, 421, 553, 353,
       431, 522, 205, 204, 532, 387, 150, 418, 163])

In [11]:
training_index = random_index[:int(len(Y) * .8)]
test_index = random_index[int(len(Y) * .8):] 

In [12]:
x_train = X[training_index]
x_test = X[test_index]
y_train  = Y[training_index]
y_test = Y[test_index]

In [13]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [14]:
# Train-Test split using Scikit-Learn Module
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=22)

In [15]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [16]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression()

logreg.fit(x_train, y_train)
logreg.predict(x_test) == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [18]:
accuracy = sum(logreg.predict(x_test) == y_test) / len(y_test)
accuracy

0.97368421052631582

In [19]:
error = 1- accuracy
error

0.026315789473684181

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(logreg.predict(x_test), y_test)

0.97368421052631582

In [48]:
y_test = logreg.predict(x_test)
y_test[:5]

array([0, 1, 1, 1, 0])

In [49]:
y_score = logreg.predict_proba(x_test)[:,1]
y_score[:5]

array([ 0.01289922,  0.99999998,  0.99998104,  0.99804073,  0.16760784])

In [46]:
import numpy as np
from sklearn import metrics

fpr, tpr, thresholds = metrics.roc_curve(y_test, y_score, pos_label=1)

In [47]:
metrics.auc(fpr, tpr)

0.0

In [54]:
fpr = dict()
tpr = dict()
roc_auc = dict()
# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = metrics.roc_curve(y_test.ravel(), y_score.ravel())
roc_auc["micro"] = metrics.auc(fpr["micro"], tpr["micro"])

In [58]:
import matplotlib.pyplot as plt

plt.figure()
lw = 2
plt.plot(fpr, tpr, color='darkorange',
         lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
plt.show()

TypeError: a float is required